apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cronjob-container
            image: busybox
            command: ["/bin/sh", "-c", "echo Scheduled Job Running!"]
          restartPolicy: OnFailure
